# Generated by Django 5.2 on 2025-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_paymob_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery')], max_length=50),
        ),
    ]
