# Generated by Django 5.2 on 2025-05-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
